Repository nefarius/DsHidMini, pull requests merged in 2024-05, with the labels that each got.

#361 Massive SCP DLL rewrite
  .gitignore
  .vscode/settings.json
  XInputBridge/DeviceState.cpp
  XInputBridge/DeviceState.h
  XInputBridge/GlobalState.Callbacks.cpp
  XInputBridge/GlobalState.Util.cpp
  XInputBridge/GlobalState.XInput.cpp
  XInputBridge/GlobalState.cpp
  XInputBridge/GlobalState.h
  XInputBridge/Macros.h
  XInputBridge/README.md
  XInputBridge/Types.h
  XInputBridge/UniUtil.h
  XInputBridge/XInputBridge.cpp
  XInputBridge/XInputBridge.vcxproj
  XInputBridge/XInputBridge.vcxproj.filters
  XInputBridge/dllmain.cpp
  XInputBridge/framework.h
  XInputBridge/vcpkg.json
  appveyor.yml
  build/Build.cs
  build/_build.csproj
  dshidmini.sln
  dshidmini.sln.DotSettings
  scpdlltester/scpdlltester.cpp
  scpdlltester/scpdlltester.vcxproj
  scpdlltester/scpdlltester.vcxproj.filters
Labels: enhancement, Core

#360 Rework pairing and host requesting
  include/DsHidMini/dshmguid.h
  sys/Configuration.c
  sys/Device.c
  sys/Ds3.c
  sys/Ds3.h
  sys/DsCommon.h
  sys/DsHidMini.json
  sys/DsHidMiniDrv.c
  sys/DsUsb.c
Labels: enhancement, USB

#364 Adds workarounds for wireless quirks of various controller models
  dshidmini.sln.DotSettings
  sys/Device.c
  sys/Device.h
  sys/Ds3.c
  sys/Ds3.h
  sys/DsBth.Timers.c
  sys/DsBth.c
  sys/DsBth.h
  sys/DsHidMini.man
  sys/Power.c
  sys/dshidmini.vcxproj
  sys/dshidmini.vcxproj.filters
Labels: enhancement, Bluetooth
